= Supernaut.FX
Sean Gilligan <https://github.com/msgilligan>
v0.1.1
:description: Supernaut.FX DI Framework README.
:supernautfx-version: 0.1.1
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://github.com/SupernautApp/SupernautFX/workflows/Gradle%20Build/badge.svg["Build Status", link="https://github.com/SupernautApp/SupernautFX/actions"]  image:https://travis-ci.com/SupernautApp/SupernautFX.svg?branch=master["Build Status", link="https://travis-ci.com/github/SupernautApp/SupernautFX/"] image:https://api.bintray.com/packages/supernautapp/maven/supernaut/images/download.svg[link="https://bintray.com/supernautapp/maven/supernaut/_latestVersion"]

// Hide Gitlab build badge until build is fixed (or removed).
// image:https://gitlab.com/SupernautApp/SupernautFX/badges/master/pipeline.svg[link="https://gitlab.com/SupernautApp/SupernautFX/pipelines",title="pipeline status"]

Supernaut.FX is a lightweight dependency injection framework for JavaFX applications. It is a wrapper around the core dependency injection capability of https://micronaut.io[Micronaut] (provided by the `micronaut-inject` JAR.) It enables the use of dependency injection in application, controller, and service objects.

CAUTION:: This is an experimental framework in early stage development. It is being used by a handful of applications in development and alpha-testing and seems to be working well so far.

== Simple and Lightweight

Although Supernaut.FX does prescribe a certain structure for an application in order to enable the injection of dependencies, it aspires to be a component library for your application with the sole concern of enabling dependency injection.

Perhaps in the future it could be used as a component by other full-featured JavaFX frameworks.

== Minimal Dependencies

Supernaut.FX introduces no new dependencies beyond what is required for JavaFX and Micronaut:

* *JavaFX* (direct dependencies on `javafx-fxml` and `javafx-graphics`)
* *Micronaut* (`micronaut-inject`)
* `slf4j-api` (also used by Micronaut)


== Modules

Supernaut.FX currently consists of 3 modules (JARs)

|===
|Module name | Purpose | Dependencies

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut/src/main/java/module-info.java[`app.supernaut`]
| Interfaces for background components (no JavaFX)
| *No dependencies!*

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut-fx/src/main/java/module-info.java[`app.supernaut.fx`]
| JavaFX application dependency injection support
| `app.supernaut`, *JavaFX*, `slf4j-api`

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut-fx-micronaut/src/main/java/module-info.java[`app.supernaut.fx.micronaut`]
| App Launcher with Micronaut dependency injection
| `app.supernaut.fx`, `micronaut-inject`
|===

Typical applications will have a *compile-time* dependency on `app.supernaut.fx` and a *runtime* dependency on `app.supernaut.fx.micronaut`.

You may also develop library modules for services depending only on `app.supernaut`.

== Features

* JavaFX-compatible Dependency Injection
** Main application class is dependency-injected
** JavaFX FXML controllers are dependency-injected
** Service object dependency injection
* Your main "application" class need not extend `javafx.application.Application`
* `BrowserService` abstraction for opening links in Web Browser (abstraction of JavaFX `HostServices`)
* Ability to customize Micronaut `BeanContext` or `ApplicationContext`

== Getting Started

There is no user guide or "Getting Started" document, yet. Fortunately the framework is very simple -- currently only a handful of relatively simple classes. To get started, use either the sample Gradle or Maven project.

=== Gradle Sample Project

The https://github.com/SupernautApp/supernaut-fx-sample-gradle[Gradle sample project] currently supports running your application via Gradle and building a jlink'ed and jpackage'd application via the https://github.com/beryx/badass-jlink-plugin[Badass Gradle JLink Plugin].

To build the jpackage'd app:

. `git clone git@github.com:SupernautApp/supernaut-fx-sample-gradle.git`
. `cd supernaut-fx-sample-gradle`
. `./gradlew jpackage`
. Open the `build/jpackage` directory and launch the native application for your platform.

Or to run the app directly from Gradle:

. `./gradlew run`

=== Maven Sample Project

The https://github.com/SupernautApp/supernaut-fx-sample-maven[Maven sample project] currently supports running your application via Maven and building a natively-compiled application via https://www.graalvm.org[GraalVM] and https://github.com/gluonhq/client-maven-plugin[Gluon Client Maven Plugin].

To build a GraalVM native-image:

. `git clone git@github.com:SupernautApp/supernaut-fx-sample-maven.git`
. `cd supernaut-fx-sample-maven`
. `mvn client:build`
. `mvn client:run` or open the `target/client` directory and launch the native application for your platform

Or to run the app directly from Maven:

. `mvn javafx:run`

== Building Supernaut

. Clone the repository
. Make sure your `JAVA_HOME` points to a JDK 11 or newer (but not greater than 15, Gradle doesn't support that yet)
. Configure a `JDK16` environment to point to a JDK 16 (currently in early access) installation
. `./gradlew buildCI buildJPackages`

The official builds are using JDK16 (early access) for the Java Toolchain, but if you want to build with JDK15, you can use:

. `./gradlew -PjavaToolchainVersion=15 buildCI buildJPackages`


To test one of the included sample apps:

. Run the sample Hello app
.. `./gradlew supernaut-fx-sample-hello:run`
. Build a `jpackage`-ed Hello app
.. `./gradlew supernaut-fx-sample-hello:jpackage`
.. Open the `supernautfx-sample-hello/build/jpackage` directory and launch the native application for your platform


== Inspired By

Supernaut.FX was inspired by two existing JavaFX DI frameworks, but is focused on JavaFX 11 and later, Java Module System, `jlink`, `jpackage`, and Micronaut. Thanks Adam Bien and Gluon for the inspiration.

* Adam Bien's http://afterburner.adam-bien.com[afterburner.fx]
* https://gluonhq.com/labs/ignite/[Gluon Ignite]

== Relationship to ConsensusJ

Supernaut.FX was developed for https://github.com/ConsensusJ/wallet-framework[ConsensusJ Wallet-Framework], but is general-purpose and can be used to add Micronaut-based DI to any JavaFX application.


== Design Goals

NOTE: If a framework or library like this already exists, please https://github.com/SupernautApp/SupernautFX/issues/3[let us know!]

We have researched https://github.com/mhrimaz/AwesomeJavaFX#frameworks[existing JavaFX frameworks] and haven't found anything that seems well-suited for the following criteria:


* Simple
** Minimizes abstraction and inheritance
** Avoids imposing architectural patterns (as much as possible with DI)
** Try to be more of a library than a framework
* Fast application launch
* Provides support for compile-time dependency injection (e.g. https://micronaut.io[Micronaut])
** Initially Micronaut-only
** Possibly in the future could use an abstraction to allow other similar DI frameworks (help wanted with this issue)
* Designed for Java apps shipped with a bundled runtime
** Applications built with JDK 15+ https://jdk.java.net/jpackage/[jpackage] (implemented)
** Applications built with https://www.graalvm.org/[GraalVM] and https://github.com/gluonhq/substrate[Gluon Substrate] (future)
* Agressively tracks latest JDK for JavaFX, recent Android versions
** JDK 11 or later for JavaFX components
** JDK 9 (maybe JDK 8 multi-release JARs?) for base interfaces and possible Android support
* Minimal dependencies, minimal transitive dependencies
** Core components in pure Java (no additional language runtime libraries)
** Keep packaged/bundled apps as small as possible
** Minimal dependencies simplifies security review
** Potential for use by other frameworks
* Compatible with Ahead-of-Time Compile tools
** Avoids use of dynamic runtime features
** Support popular Ahead-of-Time (AOT) compilation platforms
*** Android
*** https://www.graalvm.org/[GraalVM]
* Support for first-class native-looking apps (via optional, add-on components)
** Follows each platform's UI guidelines
** First-class platform integration
** *macOS* integration
*** Support for https://developer.apple.com/app-sandboxing/[App Sandbox]  and Mac App Store
*** Native-looking  https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/[macOS Menu Bar Menus] (with help from https://github.com/codecentric/NSMenuFX[NSMenuFX])
*** Integration with Apple's https://developer.apple.com/documentation/os/logging[unified logging system].
** May use additional libraries (e.g. NSMenuFX) on a specific platform
* Non-goal: reusable UI on desktop and mobile
** Android apps have option to use custom UI written with Android SDK
** iOS should have option to use UIKit
