= Supernaut.FX
Sean Gilligan <https://github.com/msgilligan>
v0.0.6
:description: Supernaut.FX DI Framework README.
:supernautfx-version: 0.0.6
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://github.com/ConsensusJ/SupernautFX/workflows/Gradle%20Build/badge.svg["Build Status", link="https://github.com/ConsensusJ/SupernautFX/actions"] image:https://travis-ci.org/ConsensusJ/SupernautFX.svg?branch=master["Build Status", link="https://travis-ci.org/ConsensusJ/SupernautFX/"] image:https://api.bintray.com/packages/consensusj/maven/supernaut/images/download.svg[link="https://bintray.com/consensusj/maven/supernaut/_latestVersion"]

Supernaut.FX is a lightweight dependency injection framework for JavaFX applications. It is a wrapper around the core dependency injection capability of https://micronaut.io[Micronaut] (provided by the `micronaut-inject-java` JAR.) It enables the use of dependency injection in application, controller, and service objects.

CAUTION:: This is an experimental framework in its very early stages. It is being used by a handful of applications in development and alpha-testing and seems to be working well so far.

== Simple and Lightweight

Although it does prescribe a certain structure for an application in order to enable the injection of dependencies, it aspires to be a component library for your application with the sole concern of enabling dependency injection.

Perhaps in the future it could be used as a component by other full-featured JavaFX frameworks.

== Minimal Dependencies

Supernaut.FX introduces no new dependencies beyond what is required for JavaFX and Micronaut:

* *JavaFX* (direct dependencies on `javafx-fxml` and `javafx-graphics`)
* *Micronaut* (`micronaut-inject-java`)
* `javax.inject` (also used by Micronaut)
* `slf4j-api` (also used by Micronaut)

== Features

* JavaFX-compatible Dependency Injection
** Main application class is dependency injected
** JavaFX FXML controllers are dependency injected
** Service object dependency injection
* Application class need not extend `javafx.application.Application`
* `BrowserService` abstraction for opening links in Web Browser (abstraction of JavaFX `HostServices`)
* Ability to customize Micronaut `ApplicationContext`
* Micronaut-powered application configuration via `.yml`, `.json`, or `.properties` files (forthcoming, see https://github.com/ConsensusJ/SupernautFX/issues/2)

== Getting Started

There is no user guide or "Getting Started" document, yet. Fortunately the framework is very simple -- currently only 5 (relatively simple) classes. To get started do the following:

. Clone the project
. Run the sample Hello app
.. `./gradlew supernautfx-hello:run`
. Build a `jpackage`-ed Hello app
.. Configure the `BADASS_JLINK_JPACKAGE_HOME` environment variable
.. `./gradlew supernautfx-hello:jpackage`
.. Open the `supernautfx-hello/build/jpackage` directory and launch the native application for your platform
. Review the https://github.com/ConsensusJ/SupernautFX/tree/master/supernautfx-hello/src/main/java/org/consensusj/supernautfx/sample/hello[source code for the Hello app]
. Review the https://github.com/ConsensusJ/SupernautFX/tree/master/supernautfx/src/main/java/org/consensusj/supernautfx[source code for Supernaut.FX]
. Start your own app!

== Inspired By

Supernaut.FX was inspired by two existing JavaFX DI frameworks, but is focused on JavaFX 11 and later and Micronaut. Thanks Adam Bien and Gluon for the inspiration.

* Adam Bien's http://afterburner.adam-bien.com[afterburner.fx]
* https://gluonhq.com/labs/ignite/[Gluon Ignite]

== Relationship to ConsensusJ

Supernaut.FX was developed for https://github.com/ConsensusJ/wallet-framework[ConsensusJ Wallet-Framework], but is general-purpose and can be used to add Micronaut-based DI to any JavaFX application.


== Design Goals

NOTE: If a framework or library like this already exists, please https://github.com/ConsensusJ/SupernautFX/issues/3[let us know!]

We have researched https://github.com/mhrimaz/AwesomeJavaFX#frameworks[existing JavaFX frameworks] and haven't found anything that seems well-suited for the following criteria:


* Simple
** Minimizes abstraction and inheritance
** Avoids imposing architectural patterns (as much as possible with DI)
** Try to be more of a library than a framework
* Fast application launch
* Provides support for compile-time dependency injection (e.g. https://micronaut.io[Micronaut])
** Initially Micronaut-only
** Possibly in the future could use an abstraction to allow other similar DI frameworks (help wanted with this issue)
* Designed for Java apps shipped with a bundled runtime
** Applications built with JDK 14 https://jdk.java.net/jpackage/[jpackage] (implemented)
** Applications built with https://www.graalvm.org/[GraalVM] and https://github.com/gluonhq/substrate[Gluon Substrate] (future)
* Agressively tracks latest JDK for JavaFX, recent Android versions
** JDK 11 or later for JavaFX components
** JDK 8 (with multi-release JARs?) for base components and Android
* Minimal dependencies, minimal transitive dependencies
** Core components in pure Java (no additional language runtimes)
** Keep packaged/bundled apps as small as possible
** Minimal dependencies simplifies security review
** Potential for use by other frameworks
* Compatible with Ahead-of-Time Compile tools
** Avoids use of dynamic runtime features
** Support popular Ahead-of-Time (AOT) compilation platforms
*** Android
*** https://www.graalvm.org/[GraalVM]
* Support for first-class native-looking apps (via optional, add-on components)
** Follows each platform's UI guidelines
** First-class platform integration
** *macOS* integration
*** Support for https://developer.apple.com/app-sandboxing/[App Sandbox]  and Mac App Store
*** Native-looking  https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/[macOS Menu Bar Menus] (with help from https://github.com/codecentric/NSMenuFX[NSMenuFX])
*** Integration with Apple's https://developer.apple.com/documentation/os/logging[unified logging system].
** May use additional libraries (e.g. NSMenuFX) on a specific platform
* Non-goal: reusable UI on desktop and mobile
** Android apps have option to use custom UI written with Android SDK
** iOS should have option to use UIKit
