= Supernaut.FX
Sean Gilligan <https://github.com/msgilligan>
v0.3.1
:description: Supernaut.FX DI Framework README.
:supernautfx-version: 0.3.1
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://github.com/SupernautApp/SupernautFX/workflows/Gradle%20Build/badge.svg["Build Status", link="https://github.com/SupernautApp/SupernautFX/actions"]  

// Hide Gitlab build badge until build is fixed (or removed).
// image:https://gitlab.com/SupernautApp/SupernautFX/badges/master/pipeline.svg[link="https://gitlab.com/SupernautApp/SupernautFX/pipelines",title="pipeline status"]

Supernaut.FX is a lightweight dependency injection framework for https://openjfx.io[JavaFX] applications. It is a wrapper above the core dependency injection capability of https://micronaut.io[Micronaut® framework] (provided by the `micronaut-inject` JAR.) It enables the use of dependency injection in application, controller, and service objects.

== Features

* JavaFX-compatible Dependency Injection
** Main application class is dependency-injected
** JavaFX FXML controllers are dependency-injected
** Service object dependency injection
* Your main application class need not extend `javafx.application.Application`
* `BrowserService` abstraction for opening links in Web Browser (abstraction of JavaFX `HostServices`)

Simple:: Supernaut.FX aspires to be a component library for your application with the _sole concern_ of enabling dependency injection.

Modern:: Supernaut.Fx is designed for _modern_ JavaFX applications that use the latest version of JavaFX (currently 17) and are built for distribution using either the https://docs.oracle.com/en/java/javase/17/docs/specs/man/jpackage.html[jpackage] tool of JDK 17 or as native images using GraalVM JDK 11 (using https://www.graalvm.org/reference-manual/native-image/[native-image] and https://github.com/gluonhq/substrate[Gluon Substrate])

Lightweight:: Supernaut.FX introduces no new dependencies beyond what is required for JavaFX and the `micronaut-inject` component of Micronaut® framework.

== Getting Started

See the _Getting Started_ section in the https://www.supernaut.app/SupernautFX/supernaut-user-guide.html[Supernaut.FX User's Guide].

A sample, "hello world"-style project is available for cloning in both https://github.com/SupernautApp/supernaut-fx-sample-maven[Maven] and https://github.com/SupernautApp/supernaut-fx-sample-gradle[Gradle] flavors.

== API Documentation

https://www.supernaut.app/SupernautFX/apidoc/[Supernaut.FX JavaDoc] is available on GitHub Pages.

== Binaries

Although the API may change, binary packages are available on https://gitlab.com/SupernautApp/SupernautFX/-/packages[GitLab.com]. You can download JARs or use the provided Maven coordinates to link to them directly from your `pom.xml` or `build.gradle`.

=== Maven

To access our GitLab Maven repository, add the following to your `pom.xml`:

[source]
----
<repositories>
  <repository>
    <id>gitlab-supernaut-maven</id>
    <url>https://gitlab.com/api/v4/projects/26584840/packages/maven</url>
  </repository>
</repositories>
----

See the https://github.com/SupernautApp/supernaut-fx-sample-maven[Maven sample application] for the details of setting up your `pom.xml`.

=== Gradle

To access our GitLab Maven repository, add the following to the `repositories` section of your `build.gradle`:

[source]
----
maven {
    url 'https://gitlab.com/api/v4/projects/26584840/packages/maven'
}
----

See the https://github.com/SupernautApp/supernaut-fx-sample-gradle[Gradle sample application] for the details of setting up your `build.gradle`.


== Modules

Supernaut.FX currently consists of 3 Java modules (JARs)

[cols="2, 2, 2a"]
|===
|Module name | Purpose | Dependencies

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut/src/main/java/module-info.java[`app.supernaut`]
| Interfaces for background components (no JavaFX)
| *No dependencies!*

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut-fx/src/main/java/module-info.java[`app.supernaut.fx`]
| JavaFX application dependency injection support
|
* `app.supernaut`
* *JavaFX*
* `slf4j-api`

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut-fx-micronaut/src/main/java/module-info.java[`app.supernaut.fx.micronaut`]
| App Launcher with dependency injection provided by Micronaut framework
|
* `app.supernaut.fx`
* `micronaut-inject`

|===

Typical applications will have a _compile-time_ dependency on `app.supernaut.fx` and a _runtime_ dependency on `app.supernaut.fx.micronaut`.

You may also develop library modules for services depending only on `app.supernaut`.

== Building Supernaut

. Clone the repository
. Make sure your `JAVA_HOME` points to a JDK 17 or newer
. `./gradlew buildCI buildJPackages`

To test one of the included sample apps:

. Run the sample Hello app
.. `./gradlew :apps:supernaut-fx-sample-hello:run`
. Build a `jpackage`-ed Hello app
.. `./gradlew :apps:supernaut-fx-sample-hello:jpackage`
.. Open the `apps/supernaut-fx-sample-hello/build/jpackage` directory and launch the native application for your platform


== Inspired By

Supernaut.FX was inspired by two existing JavaFX DI frameworks, but is focused on JavaFX 11 and later, Java Module System, `jlink`, `jpackage`, and Micronaut framework. Thanks Adam Bien and Gluon for the inspiration.

* Adam Bien's http://afterburner.adam-bien.com[afterburner.fx]
* https://gluonhq.com/labs/ignite/[Gluon Ignite]

== Design Goals

We have researched https://github.com/mhrimaz/AwesomeJavaFX#frameworks[existing JavaFX frameworks] and haven't found anything that seems well-suited for the following criteria:

* Simple
** Minimizes abstraction and inheritance
** Avoids imposing architectural patterns (as much as possible with DI)
** Try to be more of a library than a framework
* Fast application launch
* Provides support for compile-time dependency injection (e.g. via https://micronaut.io[Micronaut framework])
** Initial releases are for Micronaut framework only
** Possibly in the future could use an abstraction to allow other similar DI frameworks (help wanted with this issue)
* Designed for Java apps shipped with a bundled runtime
** Applications built with JDK 17+ https://docs.oracle.com/en/java/javase/17/docs/specs/man/jpackage.html[jpackage]
** Applications built with https://www.graalvm.org/[GraalVM] and https://github.com/gluonhq/substrate[Gluon Substrate]
* Aggressively tracks the latest JDK and JavaFX, recent Android versions
** JDK 11 or later for JavaFX components
** JDK 9 (maybe JDK 8 multi-release JARs?) for base interfaces and possible Android support
* Minimal dependencies, minimal transitive dependencies
** Core components in pure Java (no additional language runtime libraries)
** Keep packaged/bundled apps as small as possible
** Minimal dependencies simplifies security review
** Potential for use by other frameworks
* Compatible with Ahead-of-Time Compile tools
** Avoids use of dynamic runtime features
** Support popular Ahead-of-Time (AOT) compilation platforms
*** Android
*** https://www.graalvm.org/[GraalVM]
* Support for first-class native-looking apps (via optional, add-on components)
** Follows each platform's UI guidelines
** First-class platform integration
** *macOS* integration
*** Support for https://developer.apple.com/app-sandboxing/[App Sandbox]  and Mac App Store
*** Native-looking  https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/[macOS Menu Bar Menus] (with help from https://github.com/0x4a616e/NSMenuFX[NSMenuFX])
*** Integration with Apple's https://developer.apple.com/documentation/os/logging[unified logging system].
** May use additional libraries (e.g. NSMenuFX) on a specific platform
* Non-goal: reusable UI on desktop and mobile
** Android apps have option to use custom UI written with Android SDK
** iOS should have option to use UIKit
