/**
 * Module descriptor for SupernautFX Hello Sample app
 */
module org.consensusj.supernautfx.hello {
    requires org.consensusj.supernautfx;

    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.fxml;

    requires org.slf4j;
    requires org.slf4j.jul;
    requires javax.inject;

    /*
     * Although the classes in supernautfx.hello only use annotations
     * from javax.inject and do not import any Micronaut classes,
     * the Bean Definition classes generated by the Micronaut annotation process
     * run inside this module and do require Micronaut classes.
     */
    requires io.micronaut.inject;

    opens org.consensusj.supernautfx.sample.hello to javafx.graphics, javafx.fxml, java.base;
    exports org.consensusj.supernautfx.sample.hello;
    exports org.consensusj.supernautfx.sample.hello.service;
}