= SupernautFX Release Process

== Requirements

* `JAVA_HOME` set to OpenJDK 17 or later (`sdk use java 17-open`)
* `JDK17` set to a JDK 17 instance.

== Main Release Process

. Update `CHANGELOG.adoc`
. Set/verify versions in:
.. `gradle.properties` (including bump of app versions)
.. `README.adoc`
. Commit version bump and changelog.
. Full build, test
.. `./gradlew clean buildCI buildJPackages`
. Tag: `git tag -a v0.x.y -m "Release 0.x.y"`
. Push: `git push --tags origin master`
. Publish to GitLab (and GitHub) Maven repos:
.. `./gradlew publish`
. Publish User Guide and JavaDoc to GitHub Pages
.. `./gradlew sitePublish`
. Create GitHub Release

== Updating Gradle Dependency Verification configuration

NOTE:: We are not using Dependency Verification yet, but we did try to use it.

We are using Gradle's https://docs.gradle.org/current/userguide/dependency_verification.html[dependency verification] feature to verify dependencies used during the build. For now, we are verifying their "checksums" (actually SHA-256 hashes.) For now, we are using a "Trust on First Use" (ToFU) approach when we first use or update a dependency. So this means verification will detect any unexpected changes after the expected checksum is set in `gradle/verification-metadata.xml`.

After adding or updating a dependency, first set the `verify-metadata` flag in `gradle/verification-metadata.xml` to false, by editing the line to like this:

[source, xml]
----
<verify-metadata>false</verify-metadata>
----


Then produce the updated metadata in `gradle/verification-metadata.dryrun.xml`:

[source, bash]
----
./gradlew  --write-verification-metadata sha256 help --dry-run
----

Finally, use a diff utility to merge in the changes/additions to the orginal `gradle/verification-metadata.xml` file. Also makes sure to set the `verify-metadata` flag back to true:

[source, xml]
----
<verify-metadata>true</verify-metadata>
----

Now you can make sure the build works and push the changes to the Git repo.

== Announcements

. Not yet.

== After release

. Set versions back to -SNAPSHOT
.. `gradle.properties`
.. `CHANGELOG.adoc`
. Commit and push to master

== Publish Snapshot release to GitLab & GitHub Maven repos

. `./gradlew clean buildCI publish`


== Publish Snapshot release to LOCAL Maven repo

. `./gradlew clean buildCI publishToMavenLocal`


== macOS signing and verification

=== Signing Configuration

TBD.

=== Verification

See https://www.macissues.com/2015/11/06/how-to-verify-app-signatures-in-os-x/

----
codesign --verify --verbose </path/to/dot.app>
spctl --assess --verbose </path/to/dot.app>
----

to display signing info

----
codesign --display --verbose=6 </path/to/dot.app>
----

