= Supernaut.FX User's Guide
Sean Gilligan
v0.4.0, January 4, 2022: Preliminary draft
:numbered:
:toc:
:toclevels: 2

== Introduction

Supernaut.FX is a lightweight dependency injection framework for https://openjfx.io[JavaFX] applications. It is a wrapper around the core dependency injection capability of https://micronaut.io[Micronaut® framework] (provided by the `micronaut-inject` JAR.) It enables the use of dependency injection in application, controller, and service objects.

This early-draft User's Guide provides an introduction to the concepts and major classes and interfaces in the Supernaut.FX framework.

== Features and Benefits

TBD. (See the https://github.com/SupernautApp/SupernautFX#readme[README] for now.)

== Getting Started

This getting started section assumes you are already familiar with the basics of writing a JavaFX application.

=== Sample/Starter Projects on GitHub

The fastest way to get started is to clone or download one of the two sample "Hello World" projects on GitHub. There is one project that uses the Maven build system and one that uses Gradle. Currently -- due to the state of the available plugins and my limited knowledge of how to use them -- the options for deploying your applications are different on Gradle vs. Maven.


==== Gradle Sample

Using https://github.com/SupernautApp/supernaut-fx-sample-gradle[supernaut-fx-sample-gradle], via the Badass JLink Plugin, you can build native-looking macOS, Windows, and Linux applications with a bundled Java Runtime.

The Badass JLink Plugin performs an important role in converting non-modular jars (especially the Micronaut jars) to work in a modular environment.

You can also build natively-compiled images via the GluonFX Gradle Plugin and the GraalVM `native-image` capability.

==== Maven Sample

Using https://github.com/SupernautApp/supernaut-fx-sample-maven[supernaut-fx-sample-maven], via the GluonFX Maven Plugin, you can build natively-compiled macOS, Windows, and Linux applications using the GraalVM native-image tool.

==== Comparison Matrix

Eventually, you should be able to build `jpackage`'d images with Maven, as well.

.Supernaut.FX Gradle vs Maven Comparison
[cols="1, 3a, 3a"]
|===
|Build System |Features |Plugins

|Gradle
|

* build jar
* run
* build native-looking app with bundled JRE with `jpackage`
* build GraalVM natively-compiled image with GluonFX

|

* `micronaut-inject-java` annotation processor
* Java Modularity Plugin
* JavaFX Gradle Plugin
* Badass JLink Plugin
* GluonFX Gradle Plugin

|Maven
|

* build jar
* run
* build GraalVM natively-compiled image with GluonFX

|

* `micronaut-maven-plugin`
* `javafx-maven-plugin`
* `gluonfx-maven-plugin`

|===


=== Converting a simple JavaFX Application to Supernaut.FX

The following listing shows a simple hello-world style JavaFX program.

[source, java]
----
public class MinimalApp extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        var label = new Label("Hello, Earth!");
        var scene = new Scene(new StackPane(label), 300, 200);
        primaryStage.setScene(scene);
        primaryStage.setTitle("JavaFX Minimal App");
        primaryStage.show();
    }
}
----

By simply replacing `extends Application` with `implements ApplicationDelegate` and using the `launch()` method of the `FXLauncher` service found with the default `find()` method, it becomes a Supernaut.FX application. Also note that the `jakarta.inject` `@Singleton` annotation has been added.

[source, java]
----
@Singleton
public class MinimalApp implements ApplicationDelegate {

    public static void main(String[] args) {
        FxLauncher.find().launch(args, MinimalApp.class);
    }

    @Override
    public void start(Stage primaryStage) {
        var label = new Label("Hello, Earth!");
        var scene = new Scene(new StackPane(label), 300, 200);
        primaryStage.setScene(scene);
        primaryStage.setTitle("SupernautFX Minimal App");
        primaryStage.show();
    }
}
----

This allows you to begin using Dependency Inject to configure your application. You can define an `AppConfig` class  as follows:

[source, java]
----
@Singleton
public static class AppConfig {
    /** the application name */
    public final String planetName = "Mars";
}
----

and inject it into an added constructor of `MinimalApp`:

[source, java]
----
@Singleton
public class MinimalApp implements ApplicationDelegate {
    private final static String planetName;

    public static void main(String[] args) {
        FxLauncher.find().launch(args, MinimalApp.class);
    }

    public MinimalApp(AppConfig config) {
        planetName = config.planetName;
    }

    @Override
    public void start(Stage primaryStage) {
        var label = new Label("Hello, " + planetName + "!");
        var scene = new Scene(new StackPane(label), 300, 200);
        primaryStage.setScene(scene);
        primaryStage.setTitle("SupernautFX Minimal App");
        primaryStage.show();
    }
}
----

=== Dependency Injecting FXML Controllers

To load a dependency-inject FXML controller, simply add a `FxmlLoaderFactory` to one of your injected controllers, like this:

[source, java]
----
    public MinimalApp(AppConfig config, FxmlLoaderFactory injectedLoaderFactory) {
        planetName = config.planetName;
        loaderFactory = injectedLoaderFactory;
    }
----

and then use it to load you FXML-based windows and contollers.

[source, java]
----
        FXMLLoader loader = loaderFactory.get(getFXMLUrl("MainWindow.fxml"));
        Parent root = loader.load();
----

See `HelloApp` and `MainWindowController` (links TBD) for a fully-functioning example.

=== Injecting Service Objects

See `GreetingService` (link TBD) for a functioning example.

=== Built-in Injectable Services

TBD.

* `FxmlLoaderFactory`
* `BrowserService`
* `HostServices`
* `Application`

=== Using jakarta.inject Annotations

`jakarta.inject` annotations, such as `@Singleton` and `@Named` are the preferred type of annotations to use for injection as they are equivalent to and replace the older `javax.inject` annotation.

These annotations can work with multiple dependency injection frameworks and will help you write more portable code.

=== Using Micronaut Annotations

Unfortunately, most real-world applications will need to use some of the Micronaut-provided annotations, such as `@Factory`.

=== Java Modules

Supernaut.FX currently consists of 3 Java modules (JARs)

[cols="2, 2, 2a"]
|===
|Module name | Purpose | Dependencies

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut/src/main/java/module-info.java[`app.supernaut`]
| Interfaces for background components (no JavaFX)
| *No dependencies!*

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut-fx/src/main/java/module-info.java[`app.supernaut.fx`]
| JavaFX application dependency injection support
|
* `app.supernaut`
* *JavaFX*
* `slf4j-api`

|https://github.com/SupernautApp/SupernautFX/blob/master/supernaut-fx-micronaut/src/main/java/module-info.java[`app.supernaut.fx.micronaut`]
| App Launcher with dependency injection provided by Micronaut framework
|
* `app.supernaut.fx`
* `micronaut-inject`

|===

Typical applications will have a _compile-time_ dependency on `app.supernaut.fx` and a _runtime_ dependency on `app.supernaut.fx.micronaut`.

You may also develop library modules for services depending only on `app.supernaut`.

== Reference

=== Logging

The `app.supernaut.logging.JavaLoggingSupport` class can be used to configure `java.util.logging` in a way that is GraalVM-compatible. Typically this is done as one of the first lines of the `main()` method. For example:

[source, java]
----
    public static void main(String[] args) {
        JavaLoggingSupport.configure(HelloFX.class, "app.supernaut.fx.sample");
        log.warn("Logging configured");
        FxLauncher.byName("micronaut").launch(args, HelloFX.class);
    }
----

== Multi-threaded Startup

NOTE:: This section is for advanced users only. The parallel, asynchronous launch features should be considered experimental.

Supernaut allows you to initialize _background_ services *in parallel* with the initialization of JavaFX and your _foreground_ application running on the JavaFX Application Thread. This allows you to make network requests as early as possible so that their results will be available before or shortly after display of the application main Window.

Creating a `BackgroundApplication` is optional, there is a `DefaultBackgroundApplication` that loads no services and can be used for simple applications or in early-stage development. When you are ready to add background services, you can create a `BackgroundApplication` class.

NOTE:: JavaFX provides the `Preloader` class that can display a simple window while the main window is loading. For now, Supernaut is ignoring the preloader capability and instead focusing on displaying the main window as quickly as possible and then updating it with content in the background. The philosophy of a Supernaut application is to display the main window as quickly as a preloader and then update its contents as data becomes available. In those use cases, there is little benefit to displaying a preloader window. If there is a use case that needing preloader capability and/or a contributor with a pull request adding support, Supernaut can be updated to launch an optional preloader at the appropriate time.



=== Supernaut/FX Sequence Diagrams

==== Foreground Only

This diagram shows the simplest Supernaut configuration from the perspective of the developer of a `ApplicationDelegate` (aka foreground application). It shows the four methods that an implementor _may_ implement (all but `start()` are optional) and shows the order in which they are called and what threads they are called on. This behavior is identical to a normal JavaFX app that subclasses `Application` but with the added capability of having dependencies injected into the constructor.

[plantuml, format="svg", id="foreground-seq"]
....

skinparam NoteBackgroundColor white
hide footbox

participant "Supernaut/\nMicronaut" as Supernaut #pink
participant ApplicationDelegate

[-> Supernaut : launch()
activate  Supernaut


Supernaut -> ApplicationDelegate ** : new w/inject
note right: <font color=lightgreen>JFX application thread in light green
activate ApplicationDelegate
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : constructed
deactivate  ApplicationDelegate  #LightGreen

Supernaut -> ApplicationDelegate  : init()
activate  ApplicationDelegate #DarkGreen
note right: <font color=green>JFX init thread in dark green
Supernaut <-- ApplicationDelegate : return
deactivate  ApplicationDelegate  #DarkGreen

Supernaut -> ApplicationDelegate  : start()
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : return
deactivate  ApplicationDelegate  #LightGreen


Supernaut -> ApplicationDelegate  : stop()
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : return

deactivate ApplicationDelegate  #LightGreen
deactivate ApplicationDelegate

deactivate  Supernaut
....

==== Foreground & Background

[plantuml, format="svg", id="background-seq"]
....

skinparam NoteBackgroundColor white
hide footbox

participant "Supernaut/\nMicronaut" as Supernaut #pink
participant ApplicationDelegate
participant BackgroundApplication

[-> Supernaut : launch()
activate  Supernaut

Supernaut -> BackgroundApplication ** : new w/inject
note right: <font color=pink>Supernaut init thread in pink
activate BackgroundApplication
activate BackgroundApplication #pink
Supernaut <-- BackgroundApplication : constructed
deactivate BackgroundApplication #pink

Supernaut -> BackgroundApplication : init()
activate BackgroundApplication #pink
Supernaut <-- BackgroundApplication : return
deactivate BackgroundApplication #pink

note left: <font color=lightgreen>JFX application thread in light green

Supernaut -> BackgroundApplication : start()
activate BackgroundApplication #pink
BackgroundApplication -> BackgroundApplication : start service threads
Supernaut <-- BackgroundApplication : return

note right: <font color=blue>Background application thread(s) if any in blue
activate BackgroundApplication #blue

Supernaut -> ApplicationDelegate ** : new w/inject
activate ApplicationDelegate
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : constructed
deactivate  ApplicationDelegate  #LightGreen

note left: <font color=green>JFX init thread in dark green
Supernaut -> ApplicationDelegate  : init()
activate  ApplicationDelegate #DarkGreen
Supernaut <-- ApplicationDelegate : return
deactivate  ApplicationDelegate  #DarkGreen

Supernaut -> ApplicationDelegate  : start()
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : return
deactivate  ApplicationDelegate  #LightGreen

ApplicationDelegate <- BackgroundApplication : started

Supernaut -> ApplicationDelegate  : stop()
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : return
deactivate ApplicationDelegate  #LightGreen
deactivate ApplicationDelegate

Supernaut -> BackgroundApplication  : stop()
activate  BackgroundApplication #LightGreen
BackgroundApplication -> BackgroundApplication : stop service threads
Supernaut <-- BackgroundApplication : return
deactivate  BackgroundApplication  #blue
deactivate  BackgroundApplication  #LightGreen
deactivate  BackgroundApplication


deactivate  ApplicationDelegate
deactivate  Supernaut

....

==== Foreground, Background, and Simplified Internals

[plantuml, format="svg", id="full-seq"]
....

skinparam NoteBackgroundColor white
hide footbox

participant JFX #LightGreen
participant "Supernaut/\nMicronaut" as Supernaut #pink
participant ApplicationDelegate
participant "Supernaut Launch Thread" as LaunchThread #pink
participant BackgroundApplication

[-> Supernaut : launch()
activate  Supernaut
Supernaut -> Supernaut : create thread
Supernaut -> JFX : initialize JFX
activate JFX
note right: <font color=pink>Supernaut init thread in pink
Supernaut -> LaunchThread ** : start thread
activate LaunchThread #pink

LaunchThread -> LaunchThread : ApplicationContext.build().start()
LaunchThread -> BackgroundApplication ** : new w/inject
activate BackgroundApplication
activate BackgroundApplication #pink
LaunchThread <-- BackgroundApplication : constructed
deactivate BackgroundApplication #pink

LaunchThread -> BackgroundApplication : init()
activate BackgroundApplication #pink
LaunchThread <-- BackgroundApplication : return
deactivate BackgroundApplication #pink

JFX -> Supernaut : new app
note left: <font color=lightgreen>JFX application thread in light green
activate Supernaut #LightGreen
Supernaut -> Supernaut : wait for latch
Supernaut <- LaunchThread : latch.countdown()

LaunchThread -> BackgroundApplication : start()
activate BackgroundApplication #pink
BackgroundApplication -> BackgroundApplication : start service threads
LaunchThread <-- BackgroundApplication : return

deactivate LaunchThread #pink
note right: <font color=blue>Background application thread(s) if any in blue
activate BackgroundApplication #blue



Supernaut -> ApplicationDelegate ** : new w/inject
activate ApplicationDelegate
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : constructed
deactivate  ApplicationDelegate  #LightGreen
JFX <-- Supernaut : constructed
deactivate  Supernaut  #LightGreen

JFX -> Supernaut : init app
note left: <font color=green>JFX init thread in dark green
activate Supernaut #DarkGreen
Supernaut -> ApplicationDelegate  : init()
activate  ApplicationDelegate #DarkGreen
Supernaut <-- ApplicationDelegate : return
deactivate  ApplicationDelegate  #DarkGreen
JFX <-- Supernaut : return
deactivate  Supernaut  #DarkGreen

JFX -> Supernaut : start app
activate Supernaut #LightGreen
Supernaut -> ApplicationDelegate  : start()
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : return
deactivate  ApplicationDelegate  #LightGreen
JFX <-- Supernaut : return
deactivate  Supernaut  #LightGreen

ApplicationDelegate <- BackgroundApplication : started

JFX -> Supernaut : stop app
activate Supernaut #LightGreen
Supernaut -> ApplicationDelegate  : stop()
activate  ApplicationDelegate #LightGreen
Supernaut <-- ApplicationDelegate : return
deactivate ApplicationDelegate  #LightGreen
deactivate ApplicationDelegate

Supernaut -> BackgroundApplication  : stop()
activate  BackgroundApplication #LightGreen
BackgroundApplication -> BackgroundApplication : stop service threads
Supernaut <-- BackgroundApplication : return
deactivate  BackgroundApplication  #blue
deactivate  BackgroundApplication  #LightGreen
deactivate  BackgroundApplication


JFX <-- Supernaut : return
deactivate  Supernaut  #LightGreen

deactivate  ApplicationDelegate
deactivate  Supernaut
deactivate  JFX

....



== Bibliography

* https://blog.codecentric.de/en/2015/09/javafx-how-to-easily-implement-application-preloader-2/
* https://stackoverflow.com/questions/37579645/how-do-i-start-one-thread-for-my-code-and-one-for-a-javafx-application
